version: "3.8"

services:
    db:
        container_name: db-app
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: app
            MARIADB_DATABASE: db_app
            MARIADB_USER: root
            MARIADB_PASSWORD: app
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - db-store:/var/lib/mysql
        networks:
            - network-app

    php-fpm:
        container_name: app-app
        restart: unless-stopped
        build:
            context: docker/php
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        # extra_hosts:
        #   - host.docker.internal:host-gateway
        networks:
            - network-app
        environment:
            MARIADB_HOST: db
            MARIADB_PORT: 3306
            MARIADB_DATABASE: db_app
            MARIADB_USER: root
            MARIADB_PASSWORD: app

    nginx:
        container_name: nginx-service
        restart: unless-stopped
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 9001:80
        networks:
            - network-app
        depends_on:
            - php-fpm

    phpmyadmin:
        platform: linux/x86_64
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - 91:80
        environment:
            PMA_PORT: 3306
            PMA_HOST: db
        networks:
            - network-app
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        volumes:
            - redis-data:/data
        networks:
            - network-app
    cron:
        container_name: laravel_cron
        build:
            context: .
            dockerfile: docker/cron/Dockerfile.cron
        volumes:
            - ./:/var/www
        depends_on:
            - php-fpm

volumes:
    db-store:
    redis-data:

networks:
    network-app:
        driver: bridge
